# Introduction to NumPy

In [3]:
import numpy as np

In [9]:
x = np.array(1)#scalar

In [10]:
x

array(1)

In [11]:
y = np.array([1,2,3,4])#vector

In [12]:
y

array([1, 2, 3, 4])

In [13]:
z=np.array([(2,3),(3,4),(5,6)])

In [14]:
z

array([[2, 3],
       [3, 4],
       [5, 6]])

In [15]:
x.ndim#dimension checking this data is scalar thats why dimension will be 0

0

In [16]:
y.ndim#1-D vector

1

In [17]:
z.ndim#2-D vector

2

In [20]:
x1=np.random.randn(6,7)#random number generator

In [21]:
x1

array([[-0.67357693,  0.09015604, -0.10168497,  0.46502162,  1.18773814,
        -0.00970671, -0.89384137],
       [-0.35051221,  0.01513014, -1.12300258,  1.80265302,  0.22300904,
        -0.80680452, -0.35103939],
       [ 1.69056308,  1.04151151, -0.27795951,  0.78372198, -1.08980992,
        -0.68533379, -0.71351008],
       [ 0.72972873, -0.76998618, -0.18876118,  0.50197352, -0.26235624,
         1.88475198, -1.19831076],
       [-0.94544641,  0.22230048, -1.56269215,  0.17431807,  1.03745332,
        -0.5295034 , -0.44713694],
       [ 0.34380784,  0.77794474, -0.29907203,  0.04644822,  1.12158092,
        -1.31026761, -0.14301653]])

In [22]:
x2=np.arange(11)#range generator

In [23]:
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
x1.ndim

2

In [25]:
x2.ndim

1

In [26]:
x1.shape#Shape or Row & coloumn checking

(6, 7)

In [3]:
np.ones((5 ,5), "uint8")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [4]:
x = np.array([(1,2),(2,3)])

In [5]:
x

array([[1, 2],
       [2, 3]])

In [6]:
np.ravel(x)

array([1, 2, 2, 3])

In [16]:
i = np.arange(64).reshape(4,4,4)
i

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [17]:
i = np.arange(64).reshape(2,4,8)
i

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [18]:
i = np.arange(64).reshape(4,2,8)
i

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [19]:
i = np.arange(64).reshape(2,8,4)
i

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47],
        [48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [20]:
i = np.arange(64).reshape(4,8,2)
i

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39],
        [40, 41],
        [42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59],
        [60, 61],
        [62, 63]]])

In [21]:
i = np.arange(64).reshape(8,2,4)
i

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39]],

       [[40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55]],

       [[56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [22]:
i = np.arange(64).reshape(8,4,2)
i

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53],
        [54, 55]],

       [[56, 57],
        [58, 59],
        [60, 61],
        [62, 63]]])

In [27]:
i = np.arange(64).reshape(1,8,8)
i

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]]])

In [28]:
i = np.arange(64).reshape(8,1,8)
i

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]],

       [[32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55]],

       [[56, 57, 58, 59, 60, 61, 62, 63]]])

In [29]:
i = np.arange(64).reshape(8,8,1)
i

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15]],

       [[16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]],

       [[24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30],
        [31]],

       [[32],
        [33],
        [34],
        [35],
        [36],
        [37],
        [38],
        [39]],

       [[40],
        [41],
        [42],
        [43],
        [44],
        [45],
        [46],
        [47]],

       [[48],
        [49],
        [50],
        [51],
        [52],
        [53],
        [54],
        [55]],

       [[56],
        [57],
        [58],
        [59],
        [60],
        [61],
        [62],
        [63]]])

In [30]:
i.ndim

3

In [31]:
j=np.arange(12).reshape(4,3)

In [32]:
j

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [33]:
j.ndim

2

In [36]:
l = np.array([(2,3,4),(5,7,9),(3,8,10),(7,8,9)])

In [37]:
l

array([[ 2,  3,  4],
       [ 5,  7,  9],
       [ 3,  8, 10],
       [ 7,  8,  9]])

In [38]:
j+l

array([[ 2,  4,  6],
       [ 8, 11, 14],
       [ 9, 15, 18],
       [16, 18, 20]])

In [39]:
j-l

array([[-2, -2, -2],
       [-2, -3, -4],
       [ 3, -1, -2],
       [ 2,  2,  2]])

In [40]:
j*l

array([[ 0,  3,  8],
       [15, 28, 45],
       [18, 56, 80],
       [63, 80, 99]])

In [43]:
j=np.arange(12).reshape(4,3)
j

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
l=np.arange(12).reshape(3,4)
l

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
j@l#Matrix multiplication operator @

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [47]:
np.dot(j,l)# Same like @ operator

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [49]:
j.dot(l)# same like @ operator

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155],
       [128, 158, 188, 218]])

In [53]:
x = np.array([33.2,44,55])

In [54]:
x

array([33.2, 44. , 55. ])

In [55]:
type(x)

numpy.ndarray

In [56]:
x=np.array([33,22,44],dtype="float32")

In [57]:
x

array([33., 22., 44.], dtype=float32)

In [58]:
x=np.array([33,22,44],dtype=np.float32)

In [59]:
x

array([33., 22., 44.], dtype=float32)

In [61]:
y = np.asarray(x,'int32')

In [62]:
y

array([33, 22, 44])

In [64]:
y = np.asarray(x,np.int32)

In [65]:
y

array([33, 22, 44])

In [71]:
a=np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [74]:
b =np.ones(9)
b

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
a.ndim

2

In [75]:
b.ndim

1

In [79]:
i=np.zeros((3,4))
i

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
j=np.zeros([3,4])
j

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
i.ndim

2

In [82]:
j.ndim

2

In [83]:
np.empty([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
x=np.empty(3)
x

array([33.2, 44. , 55. ])

In [86]:
x.ndim

1

In [87]:
z=np.empty([3,4])+2+np.ones([3,4])*5-1+np.zeros([3,4])

In [88]:
z

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [89]:
np.empty([3,4])+2

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [95]:
np.ones([3,4])*5-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [94]:
np.ones([3,4])*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [93]:
np.empty([3,4])

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [96]:
b=np.full((3,4),7)

In [97]:
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [98]:
b=np.full((5,6),11)

In [99]:
b

array([[11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11]])

In [100]:
c=np.ones_like(b)

In [104]:
c

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [102]:
d=np.zeros_like(c)

In [103]:
d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [105]:
e=np.empty_like(c)

In [106]:
e

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [107]:
c

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [4]:
x = np.array([(2,3,4),(4,5,6),(6,7,8)])

In [5]:
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
x[2][1]

7

In [15]:
x[0:2,0:2]

array([[2, 3],
       [4, 5]])

In [16]:
struct tree {
   int prodrule;
   char *symbolname; /* optional for Fall 2019: term or nonterm symbol name */
   int nkids;
   struct tree *kids[9]; /* if nkids >0 */
   struct token *leaf;   /* if nkids == 0; might be null */
}

int treeprint(struct tree *t, int depth)
{
  int i;

  printf("%*s %s: %d\n", depth*2, " ", humanreadable(t), t->nkids);
  
  for(i=0; i<t->nkids; i++)
    treeprint(t->kids[i], depth+1);

}

SyntaxError: invalid syntax (<ipython-input-16-995d4d432433>, line 1)